import CardsContainer from '../components/Cards/CardsContainer';
import GetStartedSection from '../components/layout/GetStartedSection';
import Head from 'next/head';
import Image from 'next/image';
import { LinkInput } from '../components/Links/LinkInput';
import { ThemeProvider } from 'styled-components';
import mypic from '../public/people working.svg';
import styled from 'styled-components';

const theme = {
  palette: {
    primary: {
      cyan: '#2acfcf',
      darkViolet: '#3b3054',
    },
    
    secondary: {
      red: '#f46262',
    },

    neutral: {
      gray: '#bfbfbf',
      grayishViolet: '#9e9aa7',
      veryDarkBlue: '#35323e',
      veryDarkViolet: '#232127',
    },
  },
  
  typography: {
    fontWeightMedium: 500,
    fontWeightBold: 700,
  },
};

const ContentBox = styled.div`
  height: auto;
  width: auto;
  color: white;
`;

const Title = styled.h1`
  margin: 0;
  padding: 0 15%;
  font-size: 80px;
  font-weight: ${(props) => props.theme.typography.fontWeightBold};
  color: black;
  text-align: center;
  line-height: 1;
  letter-spacing: 5px;
`;

const imageWrapper = {
  textAlign: 'center',
};

const SectionContainer = styled.section`
  text-align: center;
  padding: 0 25%;
  margin: 70px auto;
`;

const SubTitle = styled.h1`
  font-size: 40px;
`;
export default function Home() {
  return (
    <>
      <Head>
        <title>Shortly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <ContentBox>
          <Title>MORE THAN JUST SHORTER LINKS</Title>
          <div style={imageWrapper}>
            <Image src={mypic} alt="People Working" />
          </div>
        </ContentBox>
        <LinkInput />
        <SectionContainer>
          <SubTitle>Advanced Statistics</SubTitle>
          <p style={{ color: 'gray', fontSize: '20px' }}>
            Track how your links are performing across the web with our advanced
            statistics dashboard.
          </p>
        </SectionContainer>
        <CardsContainer />
        <GetStartedSection />
      </ThemeProvider>
    </>
  );
}
